# Generated by Django 3.2.6 on 2021-08-19 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_number', models.CharField(max_length=150, verbose_name='Номер кузова')),
            ],
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Наименование')),
                ('article', models.CharField(max_length=150, verbose_name='Артикул')),
            ],
        ),
        migrations.CreateModel(
            name='TypeOfMismatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mismatch', models.CharField(max_length=150, verbose_name='Тип несоответствия')),
            ],
        ),
        migrations.CreateModel(
            name='Workshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_workshop', models.CharField(max_length=150, verbose_name='Цех')),
                ('responsible_executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workshops_responsible_executor', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный исполнитель')),
            ],
        ),
        migrations.CreateModel(
            name='Defects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('date_defect_detection', models.DateField(verbose_name='Дата обнаружения')),
                ('term_up_to', models.DateTimeField(verbose_name='Срок до')),
                ('elimination_defect', models.BooleanField(default=False, verbose_name='Устранение дефекта')),
                ('number_of_inconsistencies', models.IntegerField(verbose_name='Количество несоответствий')),
                ('discrepancy_description', models.TextField(blank=True, verbose_name='Описание несоответствия')),
                ('photo', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/', verbose_name='Фото дефекта')),
                ('body_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects_body_number', to='defects.bodies', verbose_name='Номер кузова')),
                ('detail', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects_detail', to='defects.details', verbose_name='Деталь')),
                ('quality_controller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects_quality_controller', to=settings.AUTH_USER_MODEL, verbose_name='Контролер ОТК')),
                ('responsible_executor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects_responsible_executor', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный исполнитель')),
                ('type_of_discrepancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects_type_of_discrepancy', to='defects.typeofmismatch', verbose_name='Тип несоответствия')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects_workshop', to='defects.workshops', verbose_name='Цех')),
            ],
            options={
                'verbose_name': 'Дефект',
                'verbose_name_plural': 'Дефекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
