# Generated by Django 3.2.6 on 2021-09-02 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberOfInconsistencies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='Количество несоответствий')),
            ],
            options={
                'verbose_name': 'колличество несоответствий',
                'verbose_name_plural': 'колличество несоответствий',
            },
        ),
        migrations.AlterField(
            model_name='defects',
            name='number_of_inconsistencies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects_number_inconsistencies', to='defects.numberofinconsistencies', verbose_name='Колличество несоответствий'),
        ),
    ]
