# Generated by Django 3.2.7 on 2021-09-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defects',
            name='term_up_to',
        ),
        migrations.AddField(
            model_name='defects',
            name='for_checking',
            field=models.BooleanField(default=False),
        ),
    ]
