# Generated by Django 3.2.7 on 2021-09-28 06:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_auto_20210928_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='defects',
            name='term_up_to',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Срок до'),
            preserve_default=False,
        ),
    ]
