# Generated by Django 3.2.6 on 2021-09-02 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0002_auto_20210902_1545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='numberofinconsistencies',
            options={'verbose_name': 'колличество несоответствий', 'verbose_name_plural': 'Колличество несоответствий'},
        ),
        migrations.AlterModelOptions(
            name='priority',
            options={'verbose_name': 'приоритет дефекта', 'verbose_name_plural': 'Приоритеты дефектов'},
        ),
        migrations.AlterModelOptions(
            name='probabilityestimate',
            options={'verbose_name': 'оценка вероятности', 'verbose_name_plural': 'Оценки вероятности'},
        ),
        migrations.AlterModelOptions(
            name='scaleofconsequences',
            options={'verbose_name': 'масштаб последствий', 'verbose_name_plural': 'Масштабы последствий'},
        ),
        migrations.RemoveField(
            model_name='priority',
            name='score',
        ),
        migrations.RemoveField(
            model_name='status',
            name='score',
        ),
    ]
