# Generated by Django 3.2.6 on 2021-08-25 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_auto_20210824_1434'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photodefects',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'фото', 'verbose_name_plural': 'Фото дефектов'},
        ),
        migrations.AddField(
            model_name='defects',
            name='approved_production',
            field=models.BooleanField(default=False, verbose_name='Допущено к производству'),
        ),
        migrations.AlterField(
            model_name='defects',
            name='discrepancy_description',
            field=models.TextField(blank=True, default='Отсутствует', verbose_name='Описание несоответствия'),
        ),
        migrations.AlterField(
            model_name='photodefects',
            name='defect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='defects.defects', verbose_name='Дефект'),
        ),
    ]
