# Generated by Django 3.2.6 on 2021-09-03 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0003_auto_20210902_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='probability_estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects_probability', to='defects.probabilityestimate', verbose_name='Качественная оценка вероятности'),
        ),
    ]
