# Generated by Django 3.2.6 on 2021-09-03 10:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('defects', '0004_alter_defects_probability_estimate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='defects_priority', to='defects.priority', verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='defects',
            name='quality_controller',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects_quality_controller', to=settings.AUTH_USER_MODEL, verbose_name='Контролер ОТК'),
        ),
        migrations.AlterField(
            model_name='defects',
            name='responsible_executor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects_responsible_executor', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный исполнитель'),
        ),
    ]
