# Generated by Django 3.2.6 on 2021-09-03 11:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('defects', '0005_auto_20210903_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='quality_controller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects_quality_controller', to=settings.AUTH_USER_MODEL, verbose_name='Контролер ОТК'),
        ),
        migrations.AlterField(
            model_name='defects',
            name='responsible_executor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='defects_responsible_executor', to=settings.AUTH_USER_MODEL, verbose_name='Ответственный исполнитель'),
        ),
    ]
