# Generated by Django 3.2.6 on 2021-09-03 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0007_defects_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='number_of_inconsistencies',
            field=models.IntegerField(default=1, verbose_name='Колличество несоответствий'),
        ),
    ]
