# Generated by Django 3.2.6 on 2021-09-03 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0008_alter_defects_number_of_inconsistencies'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NumberOfInconsistencies',
        ),
    ]
