# Generated by Django 3.2.7 on 2021-10-01 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0008_alter_comments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-published_at'], 'verbose_name': 'комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
