# Generated by Django 3.2.6 on 2021-09-07 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0009_delete_numberofinconsistencies'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeofmismatch',
            name='probability_estimate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mismatch_probability_estimate', to='defects.probabilityestimate', verbose_name='Оценка вероятности'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='typeofmismatch',
            name='scale_consequences',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='mismatch_scale_consequences', to='defects.scaleofconsequences', verbose_name='Масштаб последствий'),
            preserve_default=False,
        ),
    ]
