# Generated by Django 3.2.6 on 2021-09-07 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0010_auto_20210907_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defects',
            name='probability_estimate',
        ),
        migrations.RemoveField(
            model_name='defects',
            name='scale_of_consequences',
        ),
    ]
