# Generated by Django 3.2.6 on 2021-09-07 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0011_auto_20210907_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defects',
            name='risk_level',
        ),
    ]
