# Generated by Django 3.2.7 on 2021-09-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0012_remove_defects_risk_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='defects',
            name='risk_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
