# Generated by Django 3.2.7 on 2021-09-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0013_defects_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defects',
            name='risk_level',
            field=models.CharField(max_length=210),
        ),
    ]
