# Generated by Django 3.2.7 on 2021-09-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0014_alter_defects_risk_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defects',
            name='risk_level',
        ),
    ]
