# Generated by Django 3.2.7 on 2021-09-09 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('defects', '0015_remove_defects_risk_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='article',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
